---
rke2_cluster:
  children:
    rke2_servers:
      hosts:
        10.0.128.10:
          node_name: "np-ds-dev-master-1"
          etcd_snapshot_schedule_cron: "0 */8 * * *"
    rke2_agents:
      hosts:
        10.0.128.20:
          node_name: "np-ds-dev-worker-1"