---
rke2_cluster:
  children:
    rke2_servers:
      hosts:
        10.14.9.67:
          node_name: "stlrancherloc01"
        10.14.9.68:
          node_name: "stlrancherloc02"
        10.14.9.69:
          node_name: "stlrancherloc03"



