# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
  labels:
    rke2-upgrade: agent
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: kubernetes.io/os, operator: In, values: ["linux"]}
      # When using k8s version 1.19 or older, swap control-plane with master
      - {key: node-role.kubernetes.io/control-plane, operator: NotIn, values: ["true"]}
      # Optionally limit the upgrade to nodes that have an "rke2-upgrade" label, and
      # exclude nodes where the label value is "disabled" or "false". To upgrade all
      # agent nodes, remove the following two items.
      - {key: rke2-upgrade, operator: Exists}
      - {key: rke2-upgrade, operator: NotIn, values: ["disabled", "false"]}
  serviceAccountName: system-upgrade
  cordon: true
  drain:
    force: true
  upgrade:
    image: nexus.necipulusoy.com/rancher/rke2-upgrade
  version: v1.32.3+rke2r1
